### PR TITLE
Use --nginx option

### PR DESCRIPTION
**Pull request by Superpiffer**
I've tested this option and it works perfectly. Why not use it?

### CODE REVIEW

**Comment by lnicola** [comment]
Thank you. I'll have to look into this. Not so long ago it was failing for me due to https://github.com/certbot/certbot/issues/921. It also used to overwrite portions of `nginx.conf` with older versions.

Apparently, it's working better now, but I'm still somewhat suspicious.

Two questions:

 - is `--nginx` required? I think it remembers the authenticator, so it's only needed once
 - is the `systemctl reload nginx` hook required?

And we'll also want to update the README with instructions for setting it up. Keeping the `webroot` section might not be bad, as it can be quite useful.

**Comment by Superpiffer** [comment]
1) I didn't know that certbot remembers the authenticator, so maybe this pull request is useless. 
2) I thought that I had the last version of the service file but I'm using "ExecStopPost=/bin/systemctl --no-block reload nginx" as the last release on AUR. It works just fine so I'm not really sure that the hook is needed or not. My mistake!

**Comment by lnicola** [comment]
Sorry. I did some more tests, and it seems to be stable. To answer my questions:

> is --nginx required? I think it remembers the authenticator, so it's only needed once

The renewal config file gets updated with the new authenticator, so there's no need to pass `--nginx` every time.

> is the systemctl reload nginx hook required?

No, `certbot-nginx` does that automatically.

Given the two points above, the only remaining thing this package could do is simply run `certbot renew`, but then it should be renamed. There is, however, an unrelated `certbot-systemd` AUR package that does exactly that (it also runs `systemctl reload nginx`, which is useless).

So it looks like I should drop this package in favor of `certbot-systemd`. What do you think?

**Comment by lnicola** [comment]
See also the discussion in https://github.com/parchd-1/certbot-systemd/issues/1.

**Comment by Superpiffer** [comment]
I think you're right, infact I already switched to certbot-systemd without issues.

**Comment by lnicola** [comment]
Closed in https://github.com/lnicola/certbot-systemd-nginx/commit/4d7478d1ca4788b042cfdb0fff26d12955916b5e.

**Pull request closed without merging**
